import { Inter } from "next/font/google";
import "./globals.css";
import CustomRootProvider from "@/components/RootProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const session = getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomRootProvider session={session}>{children}</CustomRootProvider>
      </body>
    </html>
  );
}
